name: Shell check

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Shell check
        run: ./shellcheck.sh
